version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - 443:443
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - 80:80
    environment:
      - REACT_APP_SECRET_BACKEND_URL=/api

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
